#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "[post-rewrite hook: $1]"
changedfiles=( `git diff-tree --no-commit-id --name-only HEAD@{1} HEAD` )

if [[ "${changedfiles[*]}" =~ ".gitmodules" ]]; then
    echo "initializing & updating submodule(s)"
    git submodule update --init --recursive
fi

if [[ "${changedfiles[*]}" =~ "package.json" ]]; then
    echo "npm installing"
    npm install
fi