/**
 * BrandTruth API v1
 * BrandTruth API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DashboardResponse {
    'dashboardText'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dashboardText",
            "baseName": "dashboardText",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DashboardResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

