/**
 * BrandTruth API v1
 * BrandTruth API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Driver } from './Driver';
import { HttpFile } from '../http/http';

export class DriverDetails {
    'id'?: number;
    'driverId'?: number;
    'driver'?: Driver;
    'essence'?: string;
    'voice'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "driverId",
            "baseName": "driverId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "driver",
            "baseName": "driver",
            "type": "Driver",
            "format": ""
        },
        {
            "name": "essence",
            "baseName": "essence",
            "type": "string",
            "format": ""
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DriverDetails.attributeTypeMap;
    }
    
    public constructor() {
    }
}

