/**
 * BrandTruth API v1
 * BrandTruth API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Factor } from './Factor';
import { HttpFile } from '../http/http';

export class FactorDetails {
    'id'?: number;
    'factorId'?: number;
    'factor'?: Factor;
    'voice'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "factorId",
            "baseName": "factorId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "factor",
            "baseName": "factor",
            "type": "Factor",
            "format": ""
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FactorDetails.attributeTypeMap;
    }
    
    public constructor() {
    }
}

