/**
 * BrandTruth API v1
 * BrandTruth API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PostSummaryDto } from './PostSummaryDto';
import { HttpFile } from '../http/http';

export class ListPostsResponse {
    'posts'?: Array<PostSummaryDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "posts",
            "baseName": "posts",
            "type": "Array<PostSummaryDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListPostsResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

