/**
 * BrandTruth API v1
 * BrandTruth API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SurveyDto } from './SurveyDto';
import { HttpFile } from '../http/http';

export class ListSurveysResponse {
    'surveys'?: Array<SurveyDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "surveys",
            "baseName": "surveys",
            "type": "Array<SurveyDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListSurveysResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

