/**
 * BrandTruth API v1
 * BrandTruth API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuestionScorer } from './QuestionScorer';
import { Survey } from './Survey';
import { HttpFile } from '../http/http';

export class Question {
    'id'?: number;
    'survey'?: Survey;
    'questionText'?: string;
    'displayOrder'?: number;
    'scorers'?: Array<QuestionScorer>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "survey",
            "baseName": "survey",
            "type": "Survey",
            "format": ""
        },
        {
            "name": "questionText",
            "baseName": "questionText",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayOrder",
            "baseName": "displayOrder",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "scorers",
            "baseName": "scorers",
            "type": "Array<QuestionScorer>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Question.attributeTypeMap;
    }
    
    public constructor() {
    }
}

